config/routes.rb
Blog::Application.routes.draw do
  resources :behats
  root to: 'opensrc#home'

  
  match '/contact',to: 'opensrc#contact'
  match '/aboutus',to: 'opensrc#about'

  
  

end

app/models/behat.rb
class Behat < ActiveRecord::Base
  attr_accessible :author, :category, :content, :title ,:description
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/behats_controller.rb
class BehatsController < ApplicationController
  # GET /behats
  # GET /behats.json
  def index
    @behats = Behat.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @behats }
    end
  end

  # GET /behats/1
  # GET /behats/1.json
  def show
    @behat = Behat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @behat }
    end
  end

  # GET /behats/new
  # GET /behats/new.json
  def new
    @behat = Behat.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @behat }
    end
  end

  # GET /behats/1/edit
  def edit
    @behat = Behat.find(params[:id])
  end

  # POST /behats
  # POST /behats.json
  def create
    @behat = Behat.new(params[:behat])

    respond_to do |format|
      if @behat.save
        format.html { redirect_to @behat, notice: 'Behat was successfully created.' }
        format.json { render json: @behat, status: :created, location: @behat }
      else
        format.html { render action: "new" }
        format.json { render json: @behat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /behats/1
  # PUT /behats/1.json
  def update
    @behat = Behat.find(params[:id])

    respond_to do |format|
      if @behat.update_attributes(params[:behat])
        format.html { redirect_to @behat, notice: 'Behat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @behat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /behats/1
  # DELETE /behats/1.json
  def destroy
    @behat = Behat.find(params[:id])
    @behat.destroy

    respond_to do |format|
      format.html { redirect_to behats_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/opensrc_controller.rb
class OpensrcController < ApplicationController
  def home
  	 @behatos = Behat.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @behatoss }
    end
  end

  def about
  end

  def content
  	 @behat = Behat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @behat }
    end
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/behats_helper.rb
module BehatsHelper
end

app/helpers/opensrc_helper.rb
module OpensrcHelper
end

app/views/behats/_form.html.erb
<div class ="test">

     <%= simple_form_for(@behat) do |f| %>
        <% if @behat.errors.any? %>
          <div id="error_explanation">
          <h2><%= pluralize(@behat.errors.count, "error") %> prohibited this behat from being saved:</h2>

            <ul>
            <% @behat.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field" >
         
          <%= f.input :category ,:input_html => {:style => 'width: 250px'} %>
        </div>
        <div class="field">
           <%= f.input :title, :input_html => {:style => 'width: 400px'} %>
        </div>
        <div class="field">
          <%= f.input :description,:input_html => {:style => 'width: 700px;height:200px'} %>
        </div>
          
        <div class="field" >
          <%= f.text_area :content, :style =>'width: 900px',:class => "tinymce", :rows => 40, :cols => 150 %>
        </div>
        <div class="field">
          <%= f.input :author %>
        </div>
        <div class="actions">
          <%= f.button :submit %>
        </div>
      <% end %>
  </div>
<%= tinymce %>

app/views/behats/edit.html.erb
<h1>Editing behat</h1>

<%= render 'form' %>

<%= link_to 'Show', @behat %> |
<%= link_to 'Back', behats_path %>

app/views/behats/index.html.erb
<h1 style="text-align:left">blogpost</h1>


<div class="row">
        
            <% @behats.each do |behat| %>
               <div class ="content">
                <h4 style="text-align:right"><%= behat.category %></h2>
                <h3><%= link_to  behat.title , behat %></h3>
                <p><%= behat.description %></p>
                <h6 style="text-align:right"><%= behat.author %></h4>
                <div class ="links">
                    <%= link_to 'Show', behat %>&nbsp;&nbsp;&nbsp;
                    <%= link_to 'Edit', edit_behat_path(behat) %>&nbsp;&nbsp;&nbsp;
                    <%= link_to 'Destroy', behat, method: :delete, data: { confirm: 'Are you sure?' } %>
                </div>
        </div>
        
        <% end %>
</div>

<br />
<%= link_to 'New Behat', new_behat_path %>

app/views/behats/new.html.erb
<h1>New behat</h1>

<%= render 'form' %>

<%= link_to 'Back', behats_path %>

app/views/behats/show.html.erb
<p id="notice"><%= notice %></p>

<div class="book-content">
<div class="row">
            <div class ="content">
            <h4 style="text-align:right"><%= @behat.category %></h2>
            <h3 style="color: #458DC9;"><%= @behat.title %></h3>
            <p><%= @behat.description %></p><br>
            <p><%= @behat.content.html_safe %></p>
            <h6 style="text-align:right"><%= @behat.author %></h4>
            
  </div>
</div>
 

</div>
<div class="links">

<%= link_to 'Back', behats_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>opensource</title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "opensource blog", '#', id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home",    root_path %></li>
              <li><%= link_to "about us",    aboutus_path %></li>
              <li><%= link_to "contact", contact_path %></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>

    <div id="side-bar">
    <a href="http://www.github.com/vxvinod">  
  <img style="position: absolute; top: 35px; left: 0; border: 0; z-index: 5;" src="https://s3.amazonaws.com/github/ribbons/forkme_left_red_aa0000.png" alt="Fork me on GitHub"></a>
</div>
    <div class="container">
      <%= yield %>
    </div>


    <footer class="footer" style="text-align:center">
  <small>
    <a href=""><b>powered by :</b> twitter bootstrap Ruby on Rails </a>
  </small>
</footer>
  </body>
</html>

app/views/opensrc/about.html.erb
<div class="center hero-unit">
  <h4><legend>Co-authored by</legend></h4>
  <p>Nirbhay patil and Vinod kumar</p>

  <h4>
    This is a kick start to contribute to dedicate to aspire towards opensource .
    Our Vision is to have visibility and share knowledge on more open source frameworks such as Behat,Cucumber,codeinception,rails.

  </h4>

  <%= link_to "Contribute your knowledge", '#', class: "btn btn-large btn-primary",id: "soon" %>

  <legend>Developed using</legend>
<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/',:id=>"ror-logo" %>
  
</div>

app/views/opensrc/contact.html.erb
<div class="center hero-unit">
  <h4><legend>Contact</legend></h4>
  <p>Nirbhay patil :nirbhay.patil@gmail.com</p><br>
  <p>Vinod kumar: vinodkmrmurugan@gmail.com</p>

  
</div>

app/views/opensrc/content.html.erb
<p id="notice"><%= notice %></p>


<div class="row">
            <div class ="content">
            <h4 style="text-align:right"><%= @behat.category %></h2>
            <h3 style="color: #458DC9;"><%= @behat.title %></h3>
            <p><%= @behat.description %></p><br>
            <p><%= @behat.content %></p>
            <h6 style="text-align:right"><%= @behat.author %></h4>
            
  </div>
 

</div>
<div class="links">

<%= link_to 'Back', behats_path %>
</div>

app/views/opensrc/home.html.erb
<h1 style="text-align:left">blogpost</h1>


<div class="row">
           
        <% @behatos.each do |behat| %>
           <div class ="content">
            <h4 style="text-align:right"><%= behat.category %></h2>
            <h2 style="text-align:left"><%= link_to  behat.title , behat %></h3>
            <p><%= behat.description %></p>
            <div class ="links">
                    <%= link_to 'Read more', behat %>&nbsp;&nbsp;&nbsp;
                    <%= link_to 'comments', "#" %>&nbsp;&nbsp;&nbsp;
                    <%=link_to time_ago_in_words(behat.created_at)+ " ago ",behat %> 
             </div>
           
          
  </div>
  </tr>
<% end %>
</div>